//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDoBySA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ComplaintId { get; set; }
        public int ComplainantId { get; set; }
        public string TargetType { get; set; }
        public int TargetId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public bool IsResolved { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
