//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDoBySA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeRequests
    {
        public int RequestId { get; set; }
        public int UserId { get; set; }
        public string TargetType { get; set; }
        public int TargetId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
