//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDoBySA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.AuthorRequests = new HashSet<AuthorRequests>();
            this.Books = new HashSet<Books>();
            this.Complaints = new HashSet<Complaints>();
            this.ReadingLists = new HashSet<ReadingLists>();
            this.Reviews = new HashSet<Reviews>();
            this.UnfreezeRequests = new HashSet<UnfreezeRequests>();
        }
    
        public int UserId { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public int RoleId { get; set; }
        public bool IsFrozen { get; set; }
        public string FrozenReason { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ICollection<AuthorRequests> AuthorRequests { get; set; }
        public virtual ICollection<Books> Books { get; set; }
        public virtual ICollection<Complaints> Complaints { get; set; }
        public virtual ICollection<ReadingLists> ReadingLists { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<UnfreezeRequests> UnfreezeRequests { get; set; }
    }
}
